### ISSUE TITLE
testsparse.c:181:61: error: NGA_Sprs_array_access_col_block64 expected 'void **' but argument is of type 'double **'

### ISSUE THREAD

**Issue by drew-parsons** [GlobalArrays/ga#361]
A debian build of ga 5.9 is failing to build the new testsparse tests adding recently in PR #351 .

It looks like the kind of tightened type definitions introduced in gcc-14, not the same as the gnu-23 definitions in gcc-15 addressed by PR #360.

An excerpt from the build log is
```
mpicc.openmpi -DHAVE_CONFIG_H -I. -I..         -Ima -I../ma -I../LinAlg/lapack+blas -Iglobal/src -I../global/src -I../global/testing -I../pario/dra -I../pario/eaf -I../pario/elio -I../pario/sf -I../ga++/src  -Ig
af2c -I../gaf2c -I../tcgmsg -I../tcgmsg/tcgmsg-mpi   -Wdate-time -D_FORTIFY_SOURCE=2   -fno-aggressive-loop-optimizations -fno-tree-slp-vectorize -std=gnu17 -g -O2 -c -o global/testing/testsparse.o ../global/tes
ting/testsparse.c
../global/testing/testsparse.c: In function 'main':
../global/testing/testsparse.c:181:61: error: passing argument 5 of 'NGA_Sprs_array_access_col_block64' from incompatible pointer type [-Wincompatible-pointer-types]
  181 |     NGA_Sprs_array_access_col_block64(s_a,iproc,&iptr,&jptr,&vptr);
      |                                                             ^~~~~
      |                                                             |
      |                                                             double **
In file included from ../global/testing/testsparse.c:6:
../global/src/ga.h:356:112: note: expected 'void **' but argument is of type 'double **'
  356 | extern void          NGA_Sprs_array_access_col_block64(int s_a, int icol, int64_t **idx, int64_t **jdx, void **val);
      |                                                                                                         ~~~~~~~^~~
../global/testing/testsparse.c:214:61: error: passing argument 5 of 'NGA_Sprs_array_access_col_block64' from incompatible pointer type [-Wincompatible-pointer-types]
  214 |     NGA_Sprs_array_access_col_block64(s_a,iproc,&iptr,&jptr,&vptr);
      |                                                             ^~~~~
      |                                                             |
      |                                                             double **
../global/src/ga.h:356:112: note: expected 'void **' but argument is of type 'double **'
  356 | extern void          NGA_Sprs_array_access_col_block64(int s_a, int icol, int64_t **idx, int64_t **jdx, void **val);
      |                                                                                                         ~~~~~~~^~~
make[5]: *** [Makefile:7188: global/testing/testsparse.o] Error 1
make[5]: Target 'global/testing/testsparse.x' not remade because of errors.
```

**Comment by edoapra** [comment]
This has been fixed in develop and the recently released 5.9 and 5.9.1
