### ISSUE TITLE
OFI port doesn't build on OSX 10.12 with clang, other warnings

### ISSUE THREAD

**Issue by jeffdaily** [GlobalArrays/ga#64]
@mshiryaev

I added the OFI port to the Travis CI testing.  On my macbook running OSX 10.12, I was unable to build the ComEx/OFI port using clang.  It can't compile the nested function.  This is important to fix if you would take a look.

```bash
../../comex/src-ofi/comex.c:2594:5: error: function definition is not allowed
      here
    {
    ^
```

There are also a significant number of warnings due to the deprecated syscall() on OSX 10.12  Here's an example:
```bash
../../comex/src-ofi/comex.c:2480:13: warning: 'syscall' is deprecated: first
      deprecated in macOS 10.12 - syscall(2) is unsupported; please switch to a
      supported interface. For SYS_kdebug_trace use kdebug_signpost().
      [-Wdeprecated-declarations]
            COMEX_OFI_LOG(DEBUG, " %d: count = %d, stride: %d\n", i, cou...
            ^
```

I needed to add `-Wno-deprecated-declarations` to my CFLAGS to silence those warnings.

I committed cc4d7071fce13f24ff0e22ebf5e4539396ac8a56 to reduce some of the warnings having to do with printf() format mismatches.

In any case, the nested function will need to be addressed.  Thanks.

**Comment by jeffdaily** [comment]
Though I'd still like to get the clang issue resolved, I built libfabric using clang and the ComEx/OFI port using gcc6.  However, when I go to run global/testing/test.x, I get the following error.

```bash
we29653:bld_ofi_gcc6 $ mpirun -n 4 ./global/testing/test.x
2017:06:02 16:21:51: ERROR: (-1): load_ofi:101 cannot load default ofi library libfabric.so, error=dlopen(libfabric.so, 2): image not found
```

This is because the dynamic library is instead `libfabric.dylib` on OSX, not `libfabric.so`.

**Comment by mshiryaev** [comment]
Hi Jeff, I will look at issue with nested functions.

Regarding to syscall on  OSX 10.12 - I think it will be hard to find machine in our lab to reproduce issue, but in anyway I will try to check (the main idea is to add OSX specific way to get thread id).

Regarding to libfabric.dylib - could you try to specify  the full path to libfaric.dylib over COMEX_OFI_LIBRARY env variable?

**Comment by jeffhammond** [comment]
@mshiryaev I have a Mac and will try to work on this.  GA-OFI definitely worked on my Mac in the past.

**Comment by mshiryaev** [comment]
@jeffhammond It would be great if you will check on your Mac.

Here are preliminary changes for OSX:

log.h
#if defined(__APPLE__) && define(__MACH__)
#include <pthread.h>
extern uint64_t tid;
pthread_threadid_np(NULL, &tid);
#define GET_TID() ((int)tid)
#else
#define GET_TID() syscall(SYS_gettid)
#endif

comex.c
#if defined(__APPLE__) && define(__MACH__)
uint64_t tid;
#endif

env.c
#if defined(__APPLE__) && define(__MACH__)
#define DEFAULT_OFI_LIB "libfabric.dylib"
#else
#define DEFAULT_OFI_LIB "libfabric.so"
#endif

**Comment by ajaypanyala** [comment]
already resolved via #65
